from application import db
from application.models import Teams, Games, Users, Picks

db.drop_all()
db.create_all()


cardinals = Teams(team_name = 'Cardinals', team_city='Arizona')
falcons = Teams(team_name = 'Falcons', team_city='Atlanta')
ravens = Teams(team_name = 'Ravens', team_city='Baltimore')
bills = Teams(team_name = 'Bills', team_city='Buffalo')
bengals = Teams(team_name = 'Bengals', team_city='Cincinnati')
browns = Teams(team_name = 'Browns', team_city='Cleveland')
panthers = Teams(team_name = 'Panthers', team_city='Carolina')
bears = Teams(team_name = 'Bears', team_city='Chicago')
cowboys = Teams(team_name = 'Cowboys', team_city='Dallas')
broncos = Teams(team_name = 'Broncos', team_city='Denver')
lions = Teams(team_name = 'Lions', team_city='Detroit')
packers = Teams(team_name = 'Packers', team_city='Green Bay')
texans = Teams(team_name = 'Texans', team_city='Heuston')
colts = Teams(team_name = 'Colts', team_city='Indianapolis')
jaguars = Teams(team_name = 'Jaguars', team_city='Jacksonville')
chiefs = Teams(team_name = 'Chiefs', team_city='Kansas City')
raiders = Teams(team_name = 'Raiders', team_city='Las Vegas')
chargers = Teams(team_name = 'Chargers', team_city='Los Angeles')
rams = Teams(team_name = 'Rams', team_city='Los Angeles')
dolphins = Teams(team_name = 'Dolphins', team_city='Miami')
vikings = Teams(team_name = 'Vikings', team_city='Minnesota')
patriots = Teams(team_name = 'Patriots', team_city='New England')
saints = Teams(team_name = 'Saints', team_city='New Orleans')
giants = Teams(team_name = 'Giants', team_city='New York')
jets = Teams(team_name = 'Jets', team_city='New York')
eagles = Teams(team_name = 'Eagles', team_city='Philadelphia')
steelers = Teams(team_name = 'Steelers', team_city='Pittsburgh')
niners = Teams(team_name = '49ers', team_city='San Francisco')
seahawks = Teams(team_name = 'Seahawks', team_city='Seattle')
buccaneers = Teams(team_name = 'Buccaneers', team_city='Tampa Bay')
titans = Teams(team_name = 'Titans', team_city='Tennessee')
commanders = Teams(team_name = 'Commanders', team_city='Washington')



teams = [cardinals,falcons,ravens,bills,bengals,browns,panthers,bears,cowboys,broncos,lions,packers,texans,colts,jaguars,chiefs,raiders,chargers,rams,dolphins,vikings,patriots,saints,giants,jets,eagles,steelers,niners,seahawks,buccaneers,titans,commanders]
for team in teams:
    db.session.add(team)
db.session.commit()

games = []
#week 1
games.append(Games(home_team = rams.id , away_team = bills.id, week_no = 1))
games.append(Games(home_team = lions.id , away_team = eagles.id, week_no = 1))
games.append(Games(home_team =  bears.id, away_team = niners.id , week_no = 1))
games.append(Games(home_team = bengals.id , away_team = steelers.id, week_no = 1))
games.append(Games(home_team = dolphins.id , away_team = patriots.id, week_no = 1))
games.append(Games(home_team =  panthers.id, away_team = browns.id, week_no = 1))
games.append(Games(home_team =  texans.id, away_team = colts.id, week_no = 1))
games.append(Games(home_team = commanders.id , away_team = jaguars.id, week_no = 1))
games.append(Games(home_team = falcons.id , away_team = saints.id , week_no = 1))
games.append(Games(home_team = jets.id , away_team = ravens.id, week_no = 1))
games.append(Games(home_team =  vikings.id, away_team = packers.id, week_no = 1))
games.append(Games(home_team = titans.id , away_team = giants.id, week_no = 1))
games.append(Games(home_team = chargers.id , away_team = raiders.id, week_no = 1))
games.append(Games(home_team = cardinals.id , away_team = chiefs.id, week_no = 1))
games.append(Games(home_team =  cowboys.id, away_team = buccaneers.id, week_no = 1))
games.append(Games(home_team =  seahawks.id, away_team = broncos.id, week_no = 1))

# #week2
games.append(Games(home_team = chiefs.id, away_team = chargers.id, week_no = 2))
games.append(Games(home_team = steelers.id, away_team = patriots.id, week_no = 2))
games.append(Games(home_team = giants.id, away_team = panthers.id, week_no = 2))
games.append(Games(home_team = browns.id, away_team = jets.id, week_no = 2))
games.append(Games(home_team = jaguars.id, away_team = colts.id, week_no = 2))
games.append(Games(home_team = ravens.id, away_team = dolphins.id, week_no = 2))
games.append(Games(home_team = saints.id, away_team = buccaneers.id, week_no = 2))
games.append(Games(home_team = lions.id, away_team = commanders.id, week_no = 2))
games.append(Games(home_team = rams.id, away_team = falcons.id , week_no = 2))
games.append(Games(home_team = niners.id, away_team = seahawks.id , week_no = 2))
games.append(Games(home_team = raiders.id, away_team = cardinals.id, week_no = 2))
games.append(Games(home_team = broncos.id, away_team = texans.id, week_no = 2))
games.append(Games(home_team = cowboys.id, away_team = bengals.id, week_no = 2))
games.append(Games(home_team = packers.id, away_team = bears.id, week_no = 2))
games.append(Games(home_team = bills.id, away_team = titans.id, week_no = 2))
games.append(Games(home_team = eagles.id, away_team = vikings.id , week_no = 2))

#week3
games.append(Games(home_team = browns.id, away_team = steelers.id, week_no = 3))
games.append(Games(home_team = dolphins.id, away_team = bills.id, week_no = 3))
games.append(Games(home_team = jets.id, away_team = bengals.id, week_no = 3))
games.append(Games(home_team = titans.id, away_team = raiders.id, week_no = 3))
games.append(Games(home_team = panthers.id, away_team = saints.id, week_no = 3))
games.append(Games(home_team = patriots.id, away_team = ravens.id, week_no = 3))
games.append(Games(home_team = vikings.id, away_team = lions.id, week_no = 3))
games.append(Games(home_team = commanders.id, away_team = eagles.id, week_no = 3))
games.append(Games(home_team = colts.id, away_team = chiefs.id, week_no = 3))
games.append(Games(home_team = bears.id, away_team = texans.id, week_no = 3))
games.append(Games(home_team = chargers.id, away_team = jaguars.id, week_no = 3))
games.append(Games(home_team = cardinals.id, away_team = rams.id, week_no = 3))
games.append(Games(home_team = buccaneers.id, away_team = packers.id, week_no = 3))
games.append(Games(home_team = seahawks.id, away_team = falcons.id, week_no = 3))
games.append(Games(home_team = broncos.id, away_team = niners.id, week_no = 3))
games.append(Games(home_team = giants.id, away_team = cowboys.id, week_no = 3))

#week4
games.append(Games(home_team = bengals.id, away_team = dolphins.id, week_no = 4))
games.append(Games(home_team = saints.id, away_team = vikings.id, week_no = 4))
games.append(Games(home_team = lions.id, away_team = seahawks.id, week_no = 4))
games.append(Games(home_team = steelers.id, away_team = jets.id, week_no = 4))
games.append(Games(home_team = giants.id, away_team = bears.id, week_no = 4))
games.append(Games(home_team = colts.id, away_team = titans.id, week_no = 4))
games.append(Games(home_team = texans.id, away_team = chargers.id, week_no = 4))
games.append(Games(home_team = falcons.id, away_team = browns.id, week_no = 4))
games.append(Games(home_team = cowboys.id, away_team = commanders.id, week_no = 4))
games.append(Games(home_team = eagles.id, away_team = jaguars.id, week_no = 4))
games.append(Games(home_team = ravens.id, away_team = bills.id, week_no = 4))
games.append(Games(home_team = panthers.id, away_team = cardinals.id, week_no = 4))
games.append(Games(home_team = raiders.id, away_team = broncos.id, week_no = 4))
games.append(Games(home_team = packers.id, away_team = patriots.id, week_no = 4))
games.append(Games(home_team = buccaneers.id, away_team = chiefs.id, week_no = 4))
games.append(Games(home_team = niners.id, away_team = rams.id, week_no = 4))


#week5
games.append(Games(home_team = broncos.id, away_team = colts.id, week_no = 5))
games.append(Games(home_team = packers.id, away_team = giants.id, week_no = 5))
games.append(Games(home_team = saints.id, away_team = seahawks.id, week_no = 5))
games.append(Games(home_team = patriots.id, away_team = lions.id, week_no = 5))
games.append(Games(home_team = browns.id, away_team = chargers.id, week_no = 5))
games.append(Games(home_team = jaguars.id, away_team = texans.id, week_no = 5))
games.append(Games(home_team = buccaneers.id, away_team = falcons.id, week_no = 5))
games.append(Games(home_team = bills.id, away_team = steelers.id, week_no = 5))
games.append(Games(home_team = jets.id, away_team = dolphins.id, week_no = 5))
games.append(Games(home_team = vikings.id, away_team = bears.id, week_no = 5))
games.append(Games(home_team = commanders.id, away_team = titans.id, week_no = 5))
games.append(Games(home_team = panthers.id, away_team = niners.id, week_no = 5))
games.append(Games(home_team = cardinals.id, away_team = eagles.id, week_no = 5))
games.append(Games(home_team = rams.id, away_team = cowboys.id, week_no = 5))
games.append(Games(home_team = ravens.id, away_team = bengals.id, week_no = 5))
games.append(Games(home_team = chiefs.id, away_team = raiders.id, week_no = 5))

#week6
games.append(Games(home_team = bears.id, away_team = commanders.id, week_no = 6))
games.append(Games(home_team = giants.id, away_team = ravens.id, week_no = 6))
games.append(Games(home_team = colts.id, away_team = jaguars.id, week_no = 6))
games.append(Games(home_team = browns.id, away_team = patriots.id, week_no = 6))
games.append(Games(home_team = saints.id, away_team = bengals.id, week_no = 6))
games.append(Games(home_team = steelers.id, away_team = buccaneers.id, week_no = 6))
games.append(Games(home_team = falcons.id, away_team = niners.id, week_no = 6))
games.append(Games(home_team = packers.id, away_team = jets.id, week_no = 6))
games.append(Games(home_team = dolphins.id, away_team = vikings.id, week_no = 6))
games.append(Games(home_team = rams.id, away_team = panthers.id, week_no = 6))
games.append(Games(home_team = seahawks.id, away_team = cardinals.id, week_no = 6))
games.append(Games(home_team = chiefs.id, away_team = bills.id, week_no = 6))
games.append(Games(home_team = eagles.id, away_team = cowboys.id, week_no = 6))
games.append(Games(home_team = chargers.id, away_team = broncos.id, week_no = 6))

#week7
games.append(Games(home_team = cardinals.id, away_team = saints.id, week_no = 7))
games.append(Games(home_team = commanders.id, away_team = packers.id, week_no = 7))
games.append(Games(home_team = ravens.id, away_team = browns.id, week_no = 7))
games.append(Games(home_team = panthers.id, away_team = buccaneers.id, week_no = 7))
games.append(Games(home_team = bengals.id, away_team = falcons.id, week_no = 7))
games.append(Games(home_team = cowboys.id, away_team = lions.id, week_no = 7))
games.append(Games(home_team = jaguars.id, away_team = giants.id, week_no = 7))
games.append(Games(home_team = titans.id, away_team = colts.id, week_no = 7))
games.append(Games(home_team = raiders.id, away_team = texans.id, week_no = 7))
games.append(Games(home_team = broncos.id, away_team = jets.id, week_no = 7))
games.append(Games(home_team = niners.id, away_team = chiefs.id, week_no = 7))
games.append(Games(home_team = chargers.id, away_team = seahawks.id, week_no = 7))
games.append(Games(home_team = dolphins.id, away_team = steelers.id, week_no = 7))
games.append(Games(home_team = patriots.id, away_team = bears.id, week_no = 7))

#week8
games.append(Games(home_team = buccaneers.id, away_team = ravens.id, week_no = 8))
games.append(Games(home_team = jaguars.id, away_team = broncos.id, week_no = 8))
games.append(Games(home_team = cowboys.id, away_team = bears.id, week_no = 8))
games.append(Games(home_team = saints.id, away_team = raiders.id, week_no = 8))
games.append(Games(home_team = eagles.id, away_team = steelers.id, week_no = 8))
games.append(Games(home_team = jets.id, away_team = patriots.id, week_no = 8))
games.append(Games(home_team = lions.id, away_team = dolphins.id, week_no = 8))
games.append(Games(home_team = falcons.id, away_team = panthers.id, week_no = 8))
games.append(Games(home_team = vikings.id, away_team = cardinals.id, week_no = 8))
games.append(Games(home_team = texans.id, away_team = titans.id, week_no = 8))
games.append(Games(home_team = seahawks.id, away_team = giants.id, week_no = 8))
games.append(Games(home_team = colts.id, away_team = commanders.id, week_no = 8))
games.append(Games(home_team = rams.id, away_team = niners.id, week_no = 8))
games.append(Games(home_team = bills.id, away_team = packers.id, week_no = 8))
games.append(Games(home_team = browns.id, away_team = bengals.id, week_no = 8))

#week9
games.append(Games(home_team = texans.id, away_team = eagles.id, week_no = 9))
games.append(Games(home_team = patriots.id, away_team = colts.id, week_no = 9))
games.append(Games(home_team = lions.id, away_team = packers.id, week_no = 9))
games.append(Games(home_team = falcons.id, away_team = chargers.id, week_no = 9))
games.append(Games(home_team = jets.id, away_team = bills.id, week_no = 9))
games.append(Games(home_team = commanders.id, away_team = vikings.id, week_no = 9))
games.append(Games(home_team = bengals.id, away_team = panthers.id, week_no = 9))
games.append(Games(home_team = jaguars.id, away_team = raiders.id, week_no = 9))
games.append(Games(home_team = bears.id, away_team = dolphins.id, week_no = 9))
games.append(Games(home_team = cardinals.id, away_team = seahawks.id, week_no = 9))
games.append(Games(home_team = buccaneers.id, away_team = rams.id, week_no = 9))
games.append(Games(home_team = chiefs.id, away_team = titans.id, week_no = 9))
games.append(Games(home_team = saints.id, away_team = ravens.id, week_no = 9))

#week10
games.append(Games(home_team = panthers.id, away_team = falcons.id, week_no = 10))
games.append(Games(home_team = buccaneers.id, away_team = seahawks.id, week_no = 10))
games.append(Games(home_team = bears.id, away_team = lions.id, week_no = 10))
games.append(Games(home_team = dolphins.id, away_team = browns.id, week_no = 10))
games.append(Games(home_team = titans.id, away_team = broncos.id, week_no = 10))
games.append(Games(home_team = bills.id, away_team = vikings.id, week_no = 10))
games.append(Games(home_team = giants.id, away_team = texans.id, week_no = 10))
games.append(Games(home_team = chiefs.id, away_team = jaguars.id, week_no = 10))
games.append(Games(home_team = steelers.id, away_team = saints.id, week_no = 10))
games.append(Games(home_team = raiders.id, away_team = colts.id, week_no = 10))
games.append(Games(home_team = rams.id, away_team = cardinals.id, week_no = 10))
games.append(Games(home_team = packers.id, away_team = cowboys.id, week_no = 10))
games.append(Games(home_team = niners.id, away_team = chargers.id, week_no = 10))
games.append(Games(home_team = eagles.id, away_team = commanders.id, week_no = 10))

#week11
games.append(Games(home_team = packers.id, away_team = titans.id, week_no = 11))
games.append(Games(home_team = falcons.id, away_team = bears.id, week_no = 11))
games.append(Games(home_team = colts.id, away_team = eagles.id, week_no = 11))
games.append(Games(home_team = patriots.id, away_team = jets.id, week_no = 11))
games.append(Games(home_team = texans.id, away_team = commanders.id, week_no = 11))
games.append(Games(home_team = saints.id, away_team = rams.id, week_no = 11))
games.append(Games(home_team = bills.id, away_team = browns.id, week_no = 11))
games.append(Games(home_team = ravens.id, away_team = panthers.id, week_no = 11))
games.append(Games(home_team = giants.id, away_team = lions.id, week_no = 11))
games.append(Games(home_team = broncos.id, away_team = raiders.id, week_no = 11))
games.append(Games(home_team = vikings.id, away_team = cowboys.id, week_no = 11))
games.append(Games(home_team = steelers.id, away_team = bengals.id, week_no = 11))
games.append(Games(home_team = chargers.id, away_team = chiefs.id, week_no = 11))
games.append(Games(home_team = cardinals.id, away_team = niners.id, week_no = 11))

#week12
games.append(Games(home_team = lions.id, away_team = bills.id, week_no = 12))
games.append(Games(home_team = cowboys.id, away_team = giants.id, week_no = 12))
games.append(Games(home_team = vikings.id, away_team = patriots.id, week_no = 12))
games.append(Games(home_team = dolphins.id, away_team = texans.id, week_no = 12))
games.append(Games(home_team = titans.id, away_team = bengals.id, week_no = 12))
games.append(Games(home_team = panthers.id, away_team = broncos.id, week_no = 12))
games.append(Games(home_team = jets.id, away_team = bears.id, week_no = 12))
games.append(Games(home_team = commanders.id, away_team = falcons.id, week_no = 12))
games.append(Games(home_team = browns.id, away_team = buccaneers.id, week_no = 12))
games.append(Games(home_team = jaguars.id, away_team = ravens.id, week_no = 12))
games.append(Games(home_team = seahawks.id, away_team = raiders.id, week_no = 12))
games.append(Games(home_team = cardinals.id, away_team = chargers.id, week_no = 12))
games.append(Games(home_team = niners.id, away_team = saints.id, week_no = 12))
games.append(Games(home_team = chiefs.id, away_team = rams.id, week_no = 12))
games.append(Games(home_team = eagles.id, away_team = packers.id, week_no = 12))
games.append(Games(home_team = colts.id, away_team = steelers.id, week_no = 12))

#week13
games.append(Games(home_team = patriots.id, away_team = bills.id, week_no = 13))
games.append(Games(home_team = bears.id, away_team = packers.id, week_no = 13))
games.append(Games(home_team = falcons.id, away_team = steelers.id, week_no = 13))
games.append(Games(home_team = vikings.id, away_team = jets.id, week_no = 13))
games.append(Games(home_team = lions.id, away_team = jaguars.id, week_no = 13))
games.append(Games(home_team = eagles.id, away_team = titans.id, week_no = 13))
games.append(Games(home_team = texans.id, away_team = browns.id, week_no = 13))
games.append(Games(home_team = giants.id, away_team = commanders.id, week_no = 13))
games.append(Games(home_team = ravens.id, away_team = broncos.id, week_no = 13))
games.append(Games(home_team = niners.id, away_team = dolphins.id, week_no = 13))
games.append(Games(home_team = rams.id, away_team = seahawks.id, week_no = 13))
games.append(Games(home_team = raiders.id, away_team = chargers.id, week_no = 13))
games.append(Games(home_team = bengals.id, away_team = chiefs.id, week_no = 13))
games.append(Games(home_team = cowboys.id, away_team = colts.id, week_no = 13))
games.append(Games(home_team = buccaneers.id, away_team = saints.id, week_no = 13))

#week14
games.append(Games(home_team = rams.id, away_team = raiders.id, week_no = 14))
games.append(Games(home_team = lions.id, away_team = vikings.id, week_no = 14))
games.append(Games(home_team = steelers.id, away_team = ravens.id, week_no = 14))
games.append(Games(home_team = bengals.id, away_team = browns.id, week_no = 14))
games.append(Games(home_team = bills.id, away_team = jets.id, week_no = 14))
games.append(Games(home_team = cowboys.id, away_team = texans.id, week_no = 14))
games.append(Games(home_team = giants.id, away_team = eagles.id, week_no = 14))
games.append(Games(home_team = titans.id, away_team = jaguars.id, week_no = 14))
games.append(Games(home_team = chargers.id, away_team = dolphins.id, week_no = 14))
games.append(Games(home_team = seahawks.id, away_team = panthers.id, week_no = 14))
games.append(Games(home_team = niners.id, away_team = buccaneers.id, week_no = 14))
games.append(Games(home_team = broncos.id, away_team = chiefs.id, week_no = 14))
games.append(Games(home_team = cardinals.id, away_team = patriots.id, week_no = 14))

#week15
games.append(Games(home_team = seahawks.id, away_team = niners.id, week_no = 15))
games.append(Games(home_team = bills.id, away_team = dolphins.id, week_no = 15))
games.append(Games(home_team = vikings.id, away_team = colts.id, week_no = 15))
games.append(Games(home_team = saints.id, away_team = falcons.id, week_no = 15))
games.append(Games(home_team = commanders.id, away_team = giants.id, week_no = 15))
games.append(Games(home_team = browns.id, away_team = ravens.id, week_no = 15))
games.append(Games(home_team = bears.id, away_team = eagles.id, week_no = 15))
games.append(Games(home_team = jets.id, away_team = lions.id, week_no = 15))
games.append(Games(home_team = panthers.id, away_team = steelers.id, week_no = 15))
games.append(Games(home_team = texans.id, away_team = chiefs.id, week_no = 15))
games.append(Games(home_team = jaguars.id, away_team = cowboys.id, week_no = 15))
games.append(Games(home_team = broncos.id, away_team = cardinals.id, week_no = 15))
games.append(Games(home_team = chargers.id, away_team = titans.id, week_no = 15))
games.append(Games(home_team = buccaneers.id, away_team = bengals.id, week_no = 15))
games.append(Games(home_team = raiders.id, away_team = patriots.id, week_no = 15))
games.append(Games(home_team = packers.id, away_team = rams.id, week_no = 15))

#week16
games.append(Games(home_team = jets.id, away_team = jaguars.id, week_no = 16))
games.append(Games(home_team = ravens.id, away_team = falcons.id, week_no = 16))
games.append(Games(home_team = panthers.id, away_team = lions.id, week_no = 16))
games.append(Games(home_team = chiefs.id, away_team = seahawks.id, week_no = 16))
games.append(Games(home_team = browns.id, away_team = saints.id, week_no = 16))
games.append(Games(home_team = titans.id, away_team = texans.id, week_no = 16))
games.append(Games(home_team = patriots.id, away_team = bengals.id, week_no = 16))
games.append(Games(home_team = vikings.id, away_team = giants.id, week_no = 16))
games.append(Games(home_team = bears.id, away_team = bills.id, week_no = 16))
games.append(Games(home_team = niners.id, away_team = commanders.id, week_no = 16))
games.append(Games(home_team = cowboys.id, away_team = eagles.id, week_no = 16))
games.append(Games(home_team = steelers.id, away_team = raiders.id, week_no = 16))
games.append(Games(home_team = dolphins.id, away_team = packers.id, week_no = 16))
games.append(Games(home_team = rams.id, away_team = broncos.id, week_no = 16))
games.append(Games(home_team = cardinals.id, away_team = buccaneers.id, week_no = 16))
games.append(Games(home_team = colts.id, away_team = chargers.id, week_no = 16))

#week17
games.append(Games(home_team = titans.id, away_team = cowboys.id, week_no = 17))
games.append(Games(home_team = ravens.id, away_team = steelers.id, week_no = 17))
games.append(Games(home_team = falcons.id, away_team = cardinals.id, week_no = 17))
games.append(Games(home_team = patriots.id, away_team = dolphins.id, week_no = 17))
games.append(Games(home_team = eagles.id, away_team = saints.id, week_no = 17))
games.append(Games(home_team = giants.id, away_team = colts.id, week_no = 17))
games.append(Games(home_team = buccaneers.id, away_team = panthers.id, week_no = 17))
games.append(Games(home_team = chiefs.id, away_team = broncos.id, week_no = 17))
games.append(Games(home_team = lions.id, away_team = bears.id, week_no = 17))
games.append(Games(home_team = commanders.id, away_team = browns.id, week_no = 17))
games.append(Games(home_team = texans.id, away_team = jaguars.id, week_no = 17))
games.append(Games(home_team = raiders.id, away_team = niners.id, week_no = 17))
games.append(Games(home_team = seahawks.id, away_team = jets.id, week_no = 17))
games.append(Games(home_team = packers.id, away_team = vikings.id, week_no = 17))
games.append(Games(home_team = chargers.id, away_team = rams.id, week_no = 17))
games.append(Games(home_team = bengals.id, away_team = bills.id, week_no = 17))

#week18
games.append(Games(home_team = niners.id, away_team = cardinals.id, week_no = 18))
games.append(Games(home_team = steelers.id, away_team = browns.id, week_no = 18))
games.append(Games(home_team = bengals.id, away_team = ravens.id, week_no = 18))
games.append(Games(home_team = bears.id, away_team = vikings.id, week_no = 18))
games.append(Games(home_team = commanders.id, away_team = cowboys.id, week_no = 18))
games.append(Games(home_team = packers.id, away_team = lions.id, week_no = 18))
games.append(Games(home_team = bills.id, away_team = patriots.id, week_no = 18))
games.append(Games(home_team = seahawks.id, away_team = rams.id, week_no = 18))
games.append(Games(home_team = dolphins.id, away_team = jets.id, week_no = 18))
games.append(Games(home_team = raiders.id, away_team = chiefs.id, week_no = 18))
games.append(Games(home_team = falcons.id, away_team = buccaneers.id, week_no = 18))
games.append(Games(home_team = eagles.id, away_team = giants.id, week_no = 18))
games.append(Games(home_team = saints.id, away_team = panthers.id, week_no = 18))
games.append(Games(home_team = broncos.id, away_team = chargers.id, week_no = 18))
games.append(Games(home_team = jaguars.id, away_team = titans.id, week_no = 18))
games.append(Games(home_team = colts.id, away_team = texans.id, week_no = 18))



for game in games:
    db.session.add(game)
db.session.commit()