from application import db
from application.models import Teams

db.drop_all()
db.create_all()

team1 = Teams(team_name = 'Cardinals', team_city='Arizona')
team2 = Teams(team_name = 'Falcons', team_city='Atlanta')
team3 = Teams(team_name = 'Ravens', team_city='Baltimore')
team4 = Teams(team_name = 'Bills', team_city='Buffalo')
team5 = Teams(team_name = 'Bengals', team_city='Cincinnati')
team6 = Teams(team_name = 'Browns', team_city='Cleveland')
team7 = Teams(team_name = 'Panthers', team_city='Carolina')
team8 = Teams(team_name = 'Bears', team_city='Chicago')
team9 = Teams(team_name = 'Cowboys', team_city='Dallas')
team10 = Teams(team_name = 'Broncos', team_city='Denver')
team11 = Teams(team_name = 'Lions', team_city='Detroit')
team12 = Teams(team_name = 'Packers', team_city='Green Bay')
team13 = Teams(team_name = 'Texans', team_city='Heuston')
team14 = Teams(team_name = 'Colts', team_city='Indianapolis')
team15 = Teams(team_name = 'Jaguars', team_city='Jacksonville')
team16 = Teams(team_name = 'Chiefs', team_city='Kansas City')
team17 = Teams(team_name = 'Raiders', team_city='Las Vegas')
team18 = Teams(team_name = 'Chargers', team_city='Los Angeles')
team19 = Teams(team_name = 'Rams', team_city='Los Angeles')
team20 = Teams(team_name = 'Dolphins', team_city='Miami')
team21 = Teams(team_name = 'Vikings', team_city='Minnesota')
team22 = Teams(team_name = 'Patriots', team_city='New England')
team23 = Teams(team_name = 'Saints', team_city='New Orleans')
team24 = Teams(team_name = 'Giants', team_city='New York')
team25 = Teams(team_name = 'Jets', team_city='New York')
team26 = Teams(team_name = 'Eagles', team_city='Philadelphia')
team27 = Teams(team_name = 'Steelers', team_city='Pittsburgh')
team28 = Teams(team_name = '49ers', team_city='San Francisco')
team29 = Teams(team_name = 'Seahawks', team_city='Seattle')
team30 = Teams(team_name = 'Buccaneers', team_city='Tampa Bay')
team31 = Teams(team_name = 'Titans', team_city='Tennessee')
team32 = Teams(team_name = 'Commanders', team_city='Washington')
teamTBC = Teams(team_name = 'TBC', team_city='TBC')

teams = [teamTBC, team1,team2,team3,team4,team5,team6,team7,team8,team9,team10,team11,team12,team13,team14,team15,team16,team17,team18,team19,team20,team21,team22,team23,team24,team25,team26,team27,team28,team29,team30,team31,team32]
for i in range(33):
    db.session.add(teams[i])
db.session.commit()